### PR TITLE
Milestone 2: User interface

### PR DESCRIPTION
**Pull request by ricardovaltierra**
The following actions were made to user-interface branch:

- Develop some steps needed to play the game
- Implement on main.rb:
     * initialize constructor method with two parameters for the player (name, team)
     * make the initial prompts to the user in order to get players information
     * make an output of the basic information for each player

### CODE REVIEW

**Comment by shshamim63** [comment]
## Status :recycle: [!! Required Changes !!] :recycle: 
___
Hi @ricardovaltierra  and @firmoholanda :wave: ,
Nice initiative :clap: , But there are some space that you need to cover to complete this milestone. And I am sure you will cover them easily. :sunglasses: 
___
#### Please follow the instructions below :point_down: to complete this milestone.
___
### :space_invader: [Mandatory Changes] :space_invader: 
___
First, all of your user interface related code should be here. So you have to think a little bit more like what other print message you should render too. 
___
1. This should tell which player's turn it is.
2. Should asks player to select from available moves.
3. Should informs player if selected move is invalid.
4. The main thing, should displays board after player move. It means the boards outlook.
5. Print the winners name.
6. Print if it is a draw.
7. Should contain a loop while the game is not over. For an example, we assign a variable called game_on as true. So it will execute while the game status is true. If we get the a winning case or result case game_on = false. Something like this :point_down: .

```
game_on = true

while game_on
  if winner # and/or draw
    game_on = false
  end
end
```
#### Please fix the above mentioned issue and send another review request.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawathossainshamim/) | [Slack](Shakhawat Hossain)

**Comment by firmoholanda** [comment]
we added at the end of each request the current program line:
1.	This should tell which player's turn it is. (line 50)
2.	Should asks player to select from available moves. (line 51)
3.	Should informs player if selected move is invalid. (line 53)
4.	The main thing, should displays board after player move. It means the boards outlook. (line 35)
5.	Print the winners name. (line 66)
6.	Print if it is a draw. (line 66)
7.	Should contain a loop while the game is not over. For an example, we assign a variable called game_on as true. So it will execute while the game status is true. If we get the a winning case or result case game_on (line 69)

**Comment by Anna-Myzukina** [comment]
### Pull Request under the review by Anna Muzykina (TSE)

**Comment by Anna-Myzukina** [comment]
### Nice job! Project looks! :+1:
WOW your README file is so descriptive 👏



### ✔️ Approved image

 #### You can merge this PR and move on with your projects. Don't forget to fill the project completion form.


*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*

**Review by Anna-Myzukina — APPROVED** [review]

**Pull request merged**
